/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.Rot13;

public class App {
    public static void main(String[] args) {
        if (args.length == 0) {
            System.err.println("Usage: ./gradlew run --args='your message here'");
            System.exit(1);
        }

        String input = String.join(" ", args);
        String output = Rot13.encode(input);
        System.out.println(output);
    }

    public void getGreeting() {
    }
}
